import { GAME_CONFIG } from './gameConfig';

export const VELOCITY_THRESHOLD = 1;
export const VELOCITY_THRESHOLD_SQUARED =
  VELOCITY_THRESHOLD * VELOCITY_THRESHOLD;

export const STOP_VELOCITY_THRESHOLD =
  GAME_CONFIG.GAME.STOP_VELOCITY_THRESHOLD;
export const STOP_VELOCITY_THRESHOLD_SQUARED =
  STOP_VELOCITY_THRESHOLD * STOP_VELOCITY_THRESHOLD;

export const FALL_THRESHOLD = GAME_CONFIG.GAME.FALL_THRESHOLD;

export const DISTANCE_UPDATE_THRESHOLD = 0.1;

export const SHOT_DETECTION_DELAY = 1000;
export const GAME_END_DELAY = GAME_CONFIG.GAME.END_DELAY;

export const SUCCESS_THRESHOLD = GAME_CONFIG.GAME.SUCCESS_THRESHOLD;
export const DROP_DISTANCE = GAME_CONFIG.GAME.DROP_DISTANCE;

